[build]
  command = "CI=false npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--no-addons"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200